name:                ASTEmitter
version:             0.1.0.0
github:              "wimvanderbauwhede/fph/CW_template"
license:             BSD3
author:              "Wim Vanderbauwhede"
maintainer:          "Wim.Vanderbauwhede@Glasgow.ac.uk"
copyright:           "2022 Wim Vanderbauwhede"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ASTEmitter#readme>

dependencies:
- base >= 4.7 && < 5
- extra
- split
- parsec
- containers 
- syb

library:
  source-dirs: src

executables:
  ASTEmitter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ASTEmitter

tests:
  ASTEmitter-test:
    main:                ASTEmitterTests.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is ASTEmitterTests
    dependencies:
    - ASTEmitter
    - hspec

